import type { Metadata } from 'next';
import './globals.css';
import Link from 'next/link';
import { selectLoggedInUser } from '@/auth/user-actions';
import { cookies } from 'next/headers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const accessToken = cookies().get('accessToken')?.value;
  const loggedInUser = await selectLoggedInUser({ accessToken });

  return (
    <html lang="en">
      <body>
        <header className="flex justify-between p-3 bg-slate-200">
          <Link href="./">risk assasment</Link>
          <p>{loggedInUser?.username}</p>
        </header>
        {children}
      </body>
    </html>
  );
}
